# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XfbBmrw_DJGttsMUYr3QUC1ZZIfFlmm
"""

import random

m1= [[0 for x in range (3)] for y in range(3)]

for i in range (3):   // satır
  for j in range (3): // sütun
    m1[i][j] = random.randint(1,101)

print(m1)

